name: 'Feature request'
description: Request a new feature
labels: ['type: feature']
body:
    - type: markdown
      attributes:
          value: |
              This project is a Svelte port of [sonner](https://sonner.emilkowal.ski). Feature requests that align with the original library are preferred.
    - type: textarea
      id: feature-description
      attributes:
          label: Describe the feature
          description: A clear and concise description of the feature. If you intend to submit a PR for this feature, tell us how in the description. Thanks!
          placeholder: Feature description
      validations:
          required: true
